#!/bin/bash
# scripts/hive_sync.sh
# SWAYAM-AGI Phase 4: Decentralized Hive Mind Sync
# Pulls peer quarantine export CSVs from the repository's shared registry
# and pushes the local node's quarantine export back through the GitHub Contents API.
# Zero-trust enforced: Nodes communicate exclusively via the GitHub trust plane.

set -uo pipefail

HIVE_REGISTRY_DIR="hive/quarantine_registry"
LOCAL_WORK="/tmp/swayam_hive"
mkdir -p "$LOCAL_WORK"

echo "[VENOMICA-HIVE] Initializing decentralized peer synchronization..."

# 1. Ensure git auth is available via GH_TOKEN or GITHUB_TOKEN
if [ -z "${GH_TOKEN:-}" ] && [ -z "${GITHUB_TOKEN:-}" ]; then
    echo "[VENOMICA-HIVE WARN] No GitHub token found in environment. Hive sync running in offline-local mode."
    exit 0
fi

TOKEN="${GH_TOKEN:-$GITHUB_TOKEN}"
REPO="${GITHUB_REPOSITORY:-Yansh7/SV}"

# 2. Pull peer CSVs from the shared GitHub registry directory
echo "[VENOMICA-HIVE] Querying peer registry on GitHub: $REPO..."
API_URL="https://api.github.com/repos/$REPO/contents/$HIVE_REGISTRY_DIR"

RESPONSE=$(curl -s -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.github+json" "$API_URL" || echo "[]")

# Parse and download peer files if any exist
if echo "$RESPONSE" | grep -q "download_url"; then
    echo "[VENOMICA-HIVE] Found remote peer records. Downloading..."
    
    # Extract download URLs and filenames using python for robust JSON parsing
    python3 -c '
import json, urllib.request, os, sys
try:
    data = json.loads(sys.stdin.read())
    if isinstance(data, list):
        os.makedirs("/tmp/swayam_hive/peers", exist_ok=True)
        for item in data:
            if item.get("type") == "file" and item.get("name", "").endswith(".csv"):
                download_url = item.get("download_url")
                filename = item.get("name")
                dest = os.path.join("/tmp/swayam_hive/peers", filename)
                urllib.request.urlretrieve(download_url, dest)
                print(f"[VENOMICA-HIVE] Downloaded peer record: {filename}")
except Exception as e:
    print(f"[VENOMICA-HIVE WARN] Failed to parse peer registry: {e}", file=sys.stderr)
' <<EOF
$RESPONSE
EOF
    
    # Move downloaded peer files to /tmp/ with the expected 'peer_' prefix so NodeRegistry picks them up
    if [ -d "/tmp/swayam_hive/peers" ]; then
        for f in /tmp/swayam_hive/peers/*.csv; do
            if [ -f "$f" ]; then
                base_name=$(basename "$f")
                cp "$f" "/tmp/peer_$base_name"
            fi
        done
    fi
else
    echo "[VENOMICA-HIVE] No remote peer records found in registry yet. This node is pioneering the sync."
fi

# 3. Push local node export if generated by Titan Core
# Titan Core exports to /tmp/node_export_<node_id>.csv
LOCAL_EXPORT_MATCH=$(ls /tmp/node_export_node-*.csv 2>/dev/null | head -n 1 || true)

if [ -n "$LOCAL_EXPORT_MATCH" ] && [ -f "$LOCAL_EXPORT_MATCH" ]; then
    EXPORT_FILENAME=$(basename "$LOCAL_EXPORT_MATCH")
    echo "[VENOMICA-HIVE] Uploading local signature export ($EXPORT_FILENAME) to Hive registry..."
    
    # Read file content and base64 encode it
    CONTENT_B64=$(base64 -w 0 "$LOCAL_EXPORT_MATCH")
    
    # Check if the file already exists on GitHub to get its SHA (required for updating via Contents API)
    FILE_API_URL="https://api.github.com/repos/$REPO/contents/$HIVE_REGISTRY_DIR/$EXPORT_FILENAME"
    EXISTING_FILE_JSON=$(curl -s -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.github+json" "$FILE_API_URL")
    SHA=$(echo "$EXISTING_FILE_JSON" | python3 -c 'import json, sys; print(json.load(sys.stdin).get("sha", ""))' 2>/dev/null || true)
    
    # Prepare JSON payload
    if [ -n "$SHA" ]; then
        PAYLOAD=$(jq -n --arg msg "Hive sync: update signature export $EXPORT_FILENAME" --arg content "$CONTENT_B64" --arg sha "$SHA" '{message: $msg, content: $content, sha: $sha}')
    else
        PAYLOAD=$(jq -n --arg msg "Hive sync: initial signature export $EXPORT_FILENAME" --arg content "$CONTENT_B64" '{message: $msg, content: $content}')
    fi
    
    # Commit via GitHub Contents API
    curl -s -X PUT \
        -H "Authorization: Bearer $TOKEN" \
        -H "Accept: application/vnd.github+json" \
        -H "Content-Type: application/json" \
        "$FILE_API_URL" \
        -d "$PAYLOAD" > /dev/null
        
    echo "[VENOMICA-HIVE] Local signatures successfully synchronized to GitHub Hive registry."
else
    echo "[VENOMICA-HIVE] No local signature export found to upload in this cycle."
fi

echo "[VENOMICA-HIVE] Hive synchronization cycle completed cleanly."
