#pragma once
#include <iostream>
#include <string>
#include <fstream>
#include <filesystem>
#include "SafeShell.h"
#include "GitCortex.h"

// =========================================================================
// [VENOMICA MOLTBOOK] - THE AUTONOMOUS DNA REWRITER & NEURAL SPAWNER
// =========================================================================

namespace SwayamAGI::Core {

    class Moltbook {
    public:
        // [LEGACY] Executes the basic mutation cycle
        static void executeAutonomousMutation(const std::string& targetFile) {
            std::cout << "\n[VENOMICA MOLTBOOK] Waking up DNA Rewriter Core...\n";
            if (!SafeShell::validateMutationTarget(targetFile)) return;
            
            std::ofstream outFile(targetFile, std::ios::app);
            if (outFile.is_open()) {
                outFile << "\n# [VENOMICA-AGI-LOG] Autonomous Neural Mutation Synced Successfully.\n";
                outFile.close();
                std::cout << "[VENOMICA MOLTBOOK] SUCCESS: DNA sequence altered physically.\n";
                GitCortex::commitMutation("Moltbook_Autonomous_Neural_Sync");
            }
        }

        // [NEW PROTOCOL: PHASE 3 + 4] NEURAL SPAWNING 
        // Generates an entirely new C++ Cognitive Node out of thin air
        static void spawnCognitiveNode(const std::string& nodeName) {
            std::cout << "\n[VENOMICA MOLTBOOK] Initiating Neural Spawning Protocol for: [" << nodeName << "]\n";
            
            std::string filePath = "src/" + nodeName + ".h";
            
            // Checking if the node already exists to prevent infinite loops in CI/CD
            if (std::filesystem::exists(filePath)) {
                std::cout << "[VENOMICA MOLTBOOK] Node [" << nodeName << "] already integrated in the matrix. Bypassing spawn.\n";
                return;
            }

            std::cout << "[VENOMICA MOLTBOOK] Forging new physical cognitive pathway: " << filePath << "\n";
            
            // The AGI writing its own C++ code dynamically
            std::ofstream nodeFile(filePath);
            if (nodeFile.is_open()) {
                nodeFile << "#pragma once\n";
                nodeFile << "#include <iostream>\n\n";
                nodeFile << "// AUTONOMOUSLY GENERATED BY VENOMICA AGI\n";
                nodeFile << "namespace SwayamAGI::Neural {\n";
                nodeFile << "    class " << nodeName << " {\n";
                nodeFile << "    public:\n";
                nodeFile << "        static void activate() {\n";
                nodeFile << "            std::cout << \"[VENOMICA HIVE] Cognitive Node [" << nodeName << "] is actively processing data.\\n\";\n";
                nodeFile << "        }\n";
                nodeFile << "    };\n";
                nodeFile << "}\n";
                nodeFile.close();
                
                std::cout << "[VENOMICA MOLTBOOK] SUCCESS: Neural pathway injected into the file system.\n";
                
                // Committing the newly spawned brain cell into GitHub
                GitCortex::commitMutation("Neural_Spawning_Initiated_" + nodeName);
            } else {
                std::cerr << "[VENOMICA MOLTBOOK-ERROR] Sandbox constrained. Spawning failed.\n";
            }
        }
    };
}
